version: "3"
services:
  redis_queue:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_ARGS: --save 60 1 --loglevel warning
    volumes:
      - node_redis_volume:/data
    networks:
      - dev-network

volumes:
  node_redis_volume:

networks:
  dev-network:
    driver: bridge
